//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARGOPOS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArgoPosEntities : DbContext
    {
        public ArgoPosEntities()
            : base("name=ArgoPosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<pos_customer> pos_customer { get; set; }
        public virtual DbSet<pos_grnheader> pos_grnheader { get; set; }
        public virtual DbSet<pos_grnitem> pos_grnitem { get; set; }
        public virtual DbSet<pos_item> pos_item { get; set; }
        public virtual DbSet<pos_itemcategory> pos_itemcategory { get; set; }
        public virtual DbSet<pos_itemstock> pos_itemstock { get; set; }
        public virtual DbSet<pos_role> pos_role { get; set; }
        public virtual DbSet<pos_sales> pos_sales { get; set; }
        public virtual DbSet<pos_salesitem> pos_salesitem { get; set; }
        public virtual DbSet<pos_supplier> pos_supplier { get; set; }
        public virtual DbSet<pos_unit> pos_unit { get; set; }
        public virtual DbSet<pos_user> pos_user { get; set; }
    }
}
