//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARGOPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class pos_itemstock
    {
        public int id { get; set; }
        public decimal initalstock { get; set; }
        public int grnid { get; set; }
        public decimal curentstock { get; set; }
        public decimal stockcost { get; set; }
        public Nullable<decimal> itemcost { get; set; }
        public string stocknumber { get; set; }
        public Nullable<int> itemid { get; set; }
    
        public virtual pos_grnheader pos_grnheader { get; set; }
        public virtual pos_item pos_item { get; set; }
    }
}
