//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARGOPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class pos_grnheader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pos_grnheader()
        {
            this.pos_grnitem = new HashSet<pos_grnitem>();
            this.pos_itemstock = new HashSet<pos_itemstock>();
        }
    
        public int id { get; set; }
        public string number { get; set; }
        public System.DateTime time { get; set; }
        public int suplier { get; set; }
        public decimal total { get; set; }
    
        public virtual pos_supplier pos_supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pos_grnitem> pos_grnitem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pos_itemstock> pos_itemstock { get; set; }
    }
}
