//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARGOPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class pos_sales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pos_sales()
        {
            this.pos_salesitem = new HashSet<pos_salesitem>();
        }
    
        public int id { get; set; }
        public string salesnumber { get; set; }
        public System.DateTime time { get; set; }
        public int customerid { get; set; }
        public decimal total { get; set; }
        public Nullable<decimal> loyltypoint { get; set; }
    
        public virtual pos_customer pos_customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pos_salesitem> pos_salesitem { get; set; }
    }
}
