//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARGOPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class pos_item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pos_item()
        {
            this.pos_itemstock = new HashSet<pos_itemstock>();
        }
    
        public int id { get; set; }
        public string itemname { get; set; }
        public int unit { get; set; }
        public string discreption { get; set; }
        public int itemcategory { get; set; }
        public decimal stock { get; set; }
    
        public virtual pos_itemcategory pos_itemcategory { get; set; }
        public virtual pos_unit pos_unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pos_itemstock> pos_itemstock { get; set; }
    }
}
