//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARGOPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class pos_grnitem
    {
        public int id { get; set; }
        public int itemid { get; set; }
        public decimal itemquntity { get; set; }
        public decimal itemcost { get; set; }
        public int grnid { get; set; }
    
        public virtual pos_grnheader pos_grnheader { get; set; }
    }
}
