//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARGOPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class pos_customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pos_customer()
        {
            this.pos_sales = new HashSet<pos_sales>();
        }
    
        public int id { get; set; }
        public string customername { get; set; }
        public string customeraddrees { get; set; }
        public int customercontact { get; set; }
        public decimal loyaltypoint { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pos_sales> pos_sales { get; set; }
    }
}
