//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARGOPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class pos_salesitem
    {
        public int id { get; set; }
        public int salesid { get; set; }
        public int itemid { get; set; }
        public decimal itemprice { get; set; }
        public decimal itemqty { get; set; }
        public Nullable<decimal> itemcost { get; set; }
    
        public virtual pos_sales pos_sales { get; set; }
    }
}
